// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGFBA.Infrastructure.DataAccess;

#nullable disable

namespace SGFBA.Infrastructure.Migrations
{
    [DbContext(typeof(SGFBADbContext))]
    [Migration("20260919131851_UpdateUserEntityMigration")]
    partial class UpdateUserEntityMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SGFBA.Domain.Entities.Acao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<Guid>("AcaoIdentifier")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FichaId")
                        .HasColumnType("bigint");

                    b.Property<long>("IdFicha")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.ToTable("acoes", (string)null);
                });

            modelBuilder.Entity("SGFBA.Domain.Entities.Estudante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StudentIdentifier")
                        .HasColumnType("char(36)");

                    b.Property<string>("TelefoneResponsavel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Turma")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("estudantes", (string)null);
                });

            modelBuilder.Entity("SGFBA.Domain.Entities.Ficha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EstudanteId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FichaIdentifier")
                        .HasColumnType("char(36)");

                    b.Property<long>("IdEstudante")
                        .HasColumnType("bigint");

                    b.Property<long>("IdOrientador")
                        .HasColumnType("bigint");

                    b.Property<int>("Motivo")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EstudanteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("fichas", (string)null);
                });

            modelBuilder.Entity("SGFBA.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SGFBA.Domain.Entities.Acao", b =>
                {
                    b.HasOne("SGFBA.Domain.Entities.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("SGFBA.Domain.Entities.Estudante", b =>
                {
                    b.HasOne("SGFBA.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGFBA.Domain.Entities.Ficha", b =>
                {
                    b.HasOne("SGFBA.Domain.Entities.Estudante", "Estudante")
                        .WithMany()
                        .HasForeignKey("EstudanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGFBA.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudante");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
