//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGFBA.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGFBA.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo não pode ter mais de 500 caracteres..
        /// </summary>
        public static string CAMPO_500_CARACTERES {
            get {
                return ResourceManager.GetString("CAMPO_500_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo informado é inválido.
        /// </summary>
        public static string CARGO_INVALIDO {
            get {
                return ResourceManager.GetString("CARGO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da ação não pode ser do futuro..
        /// </summary>
        public static string DATA_ACAO_FUTURO {
            get {
                return ResourceManager.GetString("DATA_ACAO_FUTURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da ficha não pode ser do futuro..
        /// </summary>
        public static string DATA_FICHA_DO_FUTURO {
            get {
                return ResourceManager.GetString("DATA_FICHA_DO_FUTURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de nascimento não pode ser do futuro..
        /// </summary>
        public static string DATA_NASCIMENTO_INVALID {
            get {
                return ResourceManager.GetString("DATA_NASCIMENTO_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail informado é inválido.
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório.
        /// </summary>
        public static string EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido.
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudante não encontrado..
        /// </summary>
        public static string ESTUDANTE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ESTUDANTE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de Busca Ativa não encontrada..
        /// </summary>
        public static string FICHA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("FICHA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha informados incorretos..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de matrícula deve ter 10 caracteres.
        /// </summary>
        public static string MATRICULA_10_CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_10_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de matrícula não pode ter mais de 10 caracteres.
        /// </summary>
        public static string MATRICULA_MAIOR_10_CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_MAIOR_10_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de matrícula é obrigatório.
        /// </summary>
        public static string MATRICULA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("MATRICULA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo inválido..
        /// </summary>
        public static string MOTIVO_INVALIDO {
            get {
                return ResourceManager.GetString("MOTIVO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ter mais de cem caracteres.
        /// </summary>
        public static string NOME_MAIOR_100_CARACTERES {
            get {
                return ResourceManager.GetString("NOME_MAIOR_100_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ter meos de dois caracteres.
        /// </summary>
        public static string NOME_MENOR_2_CARACTERES {
            get {
                return ResourceManager.GetString("NOME_MENOR_2_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório.
        /// </summary>
        public static string NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no mínimo 8 caracteres, sendo uma letra maiúscula, uma letra minúscula, um número e um caracter especial(ex: !,#,@,$,.).
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória.
        /// </summary>
        public static string SENHA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("SENHA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido..
        /// </summary>
        public static string STATUS_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone não pode conter mais de 11 caracteres.
        /// </summary>
        public static string TELEFONE_MAIOR_11_CARACTERES {
            get {
                return ResourceManager.GetString("TELEFONE_MAIOR_11_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone não pode ter menos que dez caracteres..
        /// </summary>
        public static string TELEFONE_MENOR_10_CARACTERES {
            get {
                return ResourceManager.GetString("TELEFONE_MENOR_10_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone do responsável é obrigatório..
        /// </summary>
        public static string TELEFONE_OBRIGATORIO {
            get {
                return ResourceManager.GetString("TELEFONE_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de ação inválida.
        /// </summary>
        public static string TIPO_ACAO_INVALIDO {
            get {
                return ResourceManager.GetString("TIPO_ACAO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turma inválida..
        /// </summary>
        public static string TURMA_INVALIDA {
            get {
                return ResourceManager.GetString("TURMA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno inválido..
        /// </summary>
        public static string TURNO_INVALIDO {
            get {
                return ResourceManager.GetString("TURNO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já registrado com a matrícula informada..
        /// </summary>
        public static string USUARIO_COM_MATRICULA_EXISTE {
            get {
                return ResourceManager.GetString("USUARIO_COM_MATRICULA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já registrado com o e-mail informado.
        /// </summary>
        public static string USUARIO_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("USUARIO_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
