//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGFBA.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGFBA.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo não pode ter mais de 500 caracteres..
        /// </summary>
        public static string CAMPO_500_CARACTERES {
            get {
                return ResourceManager.GetString("CAMPO_500_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo informado é inválido.
        /// </summary>
        public static string CARGO_INVALIDO {
            get {
                return ResourceManager.GetString("CARGO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data da ação não pode ser do futuro..
        /// </summary>
        public static string DATA_ACAO_FUTURO {
            get {
                return ResourceManager.GetString("DATA_ACAO_FUTURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data da ficha não pode ser do futuro..
        /// </summary>
        public static string DATA_FICHA_DO_FUTURO {
            get {
                return ResourceManager.GetString("DATA_FICHA_DO_FUTURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de nascimento não pode ser do futuro..
        /// </summary>
        public static string DATA_NASCIMENTO_INVALID {
            get {
                return ResourceManager.GetString("DATA_NASCIMENTO_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao desativar: usuário não encontrado..
        /// </summary>
        public static string DESATIVAR_USUARIO_ERRO {
            get {
                return ResourceManager.GetString("DESATIVAR_USUARIO_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao desativar: estudante não encontrado..
        /// </summary>
        public static string DESATIVER_ESTUDANTE_ERRO {
            get {
                return ResourceManager.GetString("DESATIVER_ESTUDANTE_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail informado é inválido.
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail é obrigatório.
        /// </summary>
        public static string EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido.
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estudante não encontrado..
        /// </summary>
        public static string ESTUDANTE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ESTUDANTE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ficha de Busca Ativa não encontrada..
        /// </summary>
        public static string FICHA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("FICHA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail ou senha informados incorretos..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de matrícula deve ter 10 caracteres.
        /// </summary>
        public static string MATRICULA_10_CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_10_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de matrícula não pode ter mais de 10 caracteres.
        /// </summary>
        public static string MATRICULA_MAIOR_10_CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_MAIOR_10_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de matrícula é obrigatório.
        /// </summary>
        public static string MATRICULA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("MATRICULA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo inválido..
        /// </summary>
        public static string MOTIVO_INVALIDO {
            get {
                return ResourceManager.GetString("MOTIVO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode ter mais de cem caracteres.
        /// </summary>
        public static string NOME_MAIOR_100_CARACTERES {
            get {
                return ResourceManager.GetString("NOME_MAIOR_100_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode ter meos de dois caracteres.
        /// </summary>
        public static string NOME_MENOR_2_CARACTERES {
            get {
                return ResourceManager.GetString("NOME_MENOR_2_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é obrigatório.
        /// </summary>
        public static string NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nível de permissão inválido..
        /// </summary>
        public static string PERMISSAO_INVALIDA {
            get {
                return ResourceManager.GetString("PERMISSAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É obrigatório informar o nível de permissão do usuário..
        /// </summary>
        public static string PERMISSAO_OBRIGATORIA {
            get {
                return ResourceManager.GetString("PERMISSAO_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha atual informada não confere com a senha já registrada..
        /// </summary>
        public static string SENHA_ATUAL_NAO_CONFERE {
            get {
                return ResourceManager.GetString("SENHA_ATUAL_NAO_CONFERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter no mínimo 8 caracteres, sendo uma letra maiúscula, uma letra minúscula, um número e um caracter especial(ex: !,#,@,$,.).
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha é obrigatória.
        /// </summary>
        public static string SENHA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("SENHA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status inválido..
        /// </summary>
        public static string STATUS_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de telefone não pode conter mais de 11 caracteres.
        /// </summary>
        public static string TELEFONE_MAIOR_11_CARACTERES {
            get {
                return ResourceManager.GetString("TELEFONE_MAIOR_11_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de telefone não pode ter menos que dez caracteres..
        /// </summary>
        public static string TELEFONE_MENOR_10_CARACTERES {
            get {
                return ResourceManager.GetString("TELEFONE_MENOR_10_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de telefone do responsável é obrigatório..
        /// </summary>
        public static string TELEFONE_OBRIGATORIO {
            get {
                return ResourceManager.GetString("TELEFONE_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de ação inválida.
        /// </summary>
        public static string TIPO_ACAO_INVALIDO {
            get {
                return ResourceManager.GetString("TIPO_ACAO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turma inválida..
        /// </summary>
        public static string TURMA_INVALIDA {
            get {
                return ResourceManager.GetString("TURMA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno inválido..
        /// </summary>
        public static string TURNO_INVALIDO {
            get {
                return ResourceManager.GetString("TURNO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário já registrado com a matrícula informada..
        /// </summary>
        public static string USUARIO_COM_MATRICULA_EXISTE {
            get {
                return ResourceManager.GetString("USUARIO_COM_MATRICULA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário já registrado com o e-mail informado.
        /// </summary>
        public static string USUARIO_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("USUARIO_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
